# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=/Program Files/java/jdk-25.0.2

    # Fabric Properties
    # check these on https://fabricmc.net/develop/
    minecraft_version=26.2
    loader_version=0.19.3
    loom_version=1.16-SNAPSHOT
    fabric_version=0.154.2+26.2

    # Mod Properties
    mod_version=26.2-1.4.3
    maven_group=io.github.itzispyder
    archives_base_name=ClickCrystals

    # Dependencies
    # check this via:
    # curl -s "https://api.modrinth.com/v2/project/modmenu/version?limit=1" | jq -r '.[0].version_number'
    modmenu_version=20.0.1