name: Build Minecraft Mod

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                minecraft-version: [
                    "1.19+build.4",
                    "1.19.1+build.6",
                    "1.19.2+build.28",
                    "1.19.3+build.5",
                    "1.19.4+build.2",
                    "1.20+build.1",
                    "1.20.1+build.10",
                    "1.20.2+build.4",
                    "1.20.3+build.1",
                    "1.20.4+build.3",
                    "1.20.5+build.1",
                    "1.20.6+build.3",
                    "1.21+build.9",
                    "1.21.1+build.3"
                ]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Set JAVA_HOME
              run: echo "JAVA_HOME=${{ runner.tool_cache }}/java/21" >> $GITHUB_ENV

            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew

            - name: Migrate Mappings
              run: ./gradlew migrateMappings --mappings "${{ matrix.minecraft-version }}"

            - name: Build Mod
              run: ./gradlew build

            - name: Rename JAR Artifact
              run: |
                  mkdir -p build/libs/renamed
                  for file in build/libs/*.jar; do
                    mv "$file" "build/libs/renamed/ClickCrystals-${{ matrix.minecraft-version }}.jar"
                  done

            - name: Upload JAR Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ClickCrystals-${{ matrix.minecraft-version }}
                  path: build/libs/renamed/ClickCrystals-${{ matrix.minecraft-version }}.jar
